Repository JesusRodriguezR/DAWPrimerParcial, pull requests merged in 2021-09, with the labels that each got.

#5 Acerca de
  AcercaDe.html
  carlos.png
Labels: PR

#6 Closes #3
  Contacto.html
  Contacto.js
  DEVELOP.md
Labels: PR

#7 Revert "Closes #3"
  Contacto.html
  Contacto.js
  DEVELOP.md
Labels: PR

#8 Closes #3
  DEVELOP.md
Labels: PR

#9 Closes #1
  Index.html
  Script.js
  img/broken.PNG
  img/clear.PNG
  img/few.PNG
  img/high-temperature.svg
  img/humidity.svg
  img/light.svg
  img/low-temperature.svg
  img/overcast.PNG
  img/scattered.PNG
Labels: PR

#11 Closes #3
  Contacto.html
  Contacto.js
Labels: PR

#12 to add hrefs
  AcercaDe.html
  Contacto.html
  Contacto.js
  Index.html
  Script.js
  carlos.png
  img/broken.PNG
  img/clear.PNG
  img/few.PNG
  img/high-temperature.svg
  img/humidity.svg
  img/light.svg
  img/low-temperature.svg
  img/overcast.PNG
  img/scattered.PNG
Labels: bug

#13 Hotfixes
  Contacto.html
  HOTFIXES.md
  Index.html
Labels: bug

#14 Release 1.1
  AcercaDe.html
  Contacto.html
  Contacto.js
  HOTFIXES.md
  Index.html
  Script.js
  carlos.png
  img/broken.PNG
  img/clear.PNG
  img/few.PNG
  img/high-temperature.svg
  img/humidity.svg
  img/light.svg
  img/low-temperature.svg
  img/overcast.PNG
  img/scattered.PNG
Labels: PR

#15 Correguir imagenes
  AcercaDe.html
  Contacto.html
  Index.html
  jesus.png
Labels: bug

#16 img bug fixed
  AcercaDe.html
  Script.js
  jesus.png
Labels: bug

#18 Grid system Contacto
  Contacto.html
Labels: enhancement, PR

#19 master merge
  AcercaDe.html
  Contacto.html
  Contacto.js
  HOTFIXES.md
  Index.html
  RELEASE.md
  Script.js
  carlos.png
  img/broken.PNG
  img/clear.PNG
  img/few.PNG
  img/high-temperature.svg
  img/humidity.svg
  img/light.svg
  img/low-temperature.svg
  img/overcast.PNG
  img/scattered.PNG
  jesus.png
Labels: PR
